
// import StudentContext from "@/context/creatStudent";
import UserProvider from "@/context/user-Provider";
import type { Metadata } from "next";

// import { Inter } from "next/font/google";
// import "./globals.css";
// import ToggleThmeContext from "@/context/toggletheme";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >

        <UserProvider>

          {children}
        
        </UserProvider>
        {/* <ToggleThmeContext> 
          {children}
          </ToggleThmeContext> */}
       </body>
    </html>
  );
}
